.TH sboclean 1 "Prickle-Prickle, The Aftermath 42, 3178 YOLD" "sbotools 1.1 fnord" dawnrazor.net
.SH NAME
.P
sboclean - clean files left around by sbotools.
.SH SYNAPSES
.P
sboclean [-h|-v] [-dwi]
.SH DESCRIPTION
.P
sboclean is used to clean files left around by sbotools, such as downloaded source files ("distfiles"), or work directories under /tmp/SBo. Note that if not run with the -i flag, sboclean will remove anything in the distfiles or /tmp/SBo folders with extreme prejudice. One of either -d or -w must be specified for this script to do anything.
.SH OPTIONS
.P
-h|--help
.RS
Show help information.
.RE
.P
-v|--version
.RS
Show version information.
.RE
.P
-d|--clean-dist
.RS
Clean distfiles, by default located at /usr/sbo/distfiles.
.RE
.P
-w|--clean-work
.RS
Clean working directories, located under /tmp/SBo.
.RE
.P
-i|--interactive
.RS
Be interactive; sboclean will ask for confirmation for each item which it thinks should be removed.
.SH BUGS
.P
None known, but there may be some. Please report any found to j@dawnrazor.net; patches are always welcome.
.SH SEE ALSO
.P
sbocheck(1), sboconfig(1), sbofind(1), sboinstall(1), sboupgrade(1), sbosnap(1), sbotools.conf(5)
.SH AUTHOR
.P
Jacob Pipkin <j@dawnrazor.net>
.P
Luke Williams <xocel@iquidus.org>
