.TH sboclean 1 "Pungenday, Confusion 37, 3182 YOLD" "sbotools 2.0" dawnrazor.net
.SH NAME
.P
sboclean - clean files left around by sbotools.
.SH SYNAPSES
.P
sboclean [-h|-v] [-dwi]
.SH DESCRIPTION
.P
sboclean is used to clean files left around by sbotools, such as downloaded source files ("distfiles"), or work directories under /tmp/SBo (or $TMP) and, for compat32 installs, under /tmp (or $TMP). Note that if not run with the -i flag, sboclean will remove anything in the distfiles or /tmp/SBo (or $TMP) folders and any /tmp/package-*-compat32 (or $TMP/package-*-compat32) directories with extreme prejudice. One of either -d or -w must be specified for this script to do anything.
.SH OPTIONS
.P
-h|--help
.RS
Show help information.
.RE
.P
-v|--version
.RS
Show version information.
.RE
.P
-d|--clean-dist
.RS
Clean distfiles, by default located at /usr/sbo/distfiles.
.RE
.P
-w|--clean-work
.RS
Clean working directories, located, by default under /tmp/SBo and, for compat32 installs, by default, /tmp.
.RE
.P
-i|--interactive
.RS
Be interactive; sboclean will ask for confirmation for each item which it thinks should be removed.
.SH EXIT CODES
.P
sboclean can exit with the following codes:
.RS

0: all operations completed successfully.
.RE
.RS
1: a usage error occurred, such as running sboclean with nothing to clean.
.RE

.SH BUGS
.P
None known, but there may be some. Please report any found to https://github.com/pink-mist/sbotools/issues ; patches are always welcome.
.SH SEE ALSO
.P
sbocheck(1), sboconfig(1), sbofind(1), sboinstall(1), sboremove(1), sbosnap(1), sboupgrade(1), sbotools.conf(5)
.SH AUTHOR
.P
Jacob Pipkin <j@dawnrazor.net>
.P
Luke Williams <xocel@iquidus.org>
.P
Andreas Guldstrand <andreas.guldstrand@gmail.com>
