.TH sbocheck 1 "Pungenday, Confusion 37, 3182 YOLD" "sbotools 2.0" dawnrazor.net
.SH NAME
.P
sbocheck - update a local slackbuilds.org tree and check for updates.
.SH SYNAPSES
.P
sbocheck [-h|-v]
.SH DESCRIPTION
.P
sbocheck first updates a previously fetched copy of the slackbuilds.org tree (see sbosnap(1)) and then checks to see if any packages installed from slackbuilds.org have updates, and reports what it finds.
.SH OPTIONS
.P
-h|--help
.RS
Show help information.
.RE
.P
-v|--version
.RS
Show version information.
.RE
.SH BUGS
.P
None known, but there may be some. Please report any found to https://github.com/pink-mist/sbotools/issues ; patches are always welcome.
.SH SEE ALSO
.P
sboclean(1), sboconfig(1), sbofind(1), sboinstall(1), sboremove(1), sbosnap(1), sboupgrade(1), sbotools.conf(5)
.SH AUTHORS
.P
Jacob Pipkin <j@dawnrazor.net>
.P
Luke Williams <xocel@iquidus.org>
.P
Andreas Guldstrand <andreas.guldstrand@gmail.com>
