.TH sboupgrade 1 "Pungenday, the 45th day of Discord in the YOLD 3178" "sbotools 0.1 fnord" dawnrazor.net
.SH NAME
.P
sboupgrade,sboinstall - install or upgrade SBos
.SH SYNAPSES
.P
sboinstall [-h] [-v] [-c TRUE|FALSE] [-d TRUE|FALSE] [-N] [-r] [-i] sbo_name (sbo_name)
.SH DESCRIPTION
.P
sboupgrade is used to upgrade packages installed from SBos. sboinstall is equivalent to sboupgrade -N, but is faster, so is preferred if only installing a new package.
.SH OPTIONS
.P
-h
.RS
Show help information.
.RE
.P
-c (TRUE|FALSE)
.RS
If TRUE, then DO NOT clean working directories after building the SBo. These are the directories where the source is unpacked and compiled, and where the package is put together in, which are under /tmp/SBo. By default, these directories are removed after building an SBo. This option leaves those directories in place. This can be set as default via the sboconfig(1) command. Also see sbotools.conf(5). This option overrides the default.
.RE
.P
-d (TRUE|FALSE)
.RS
If TRUE, then DO remove the source code after building the SBo. By default, the source code is not removed, and lives under $SBO_HOME/distfiles, which, by default, is /usr/sbo/distfiles; this option can be set as default via the sboconfig(1) command. See also sbotools.conf(5). This option overrides the default.
.RE
.P
-N
.RS
Install any new SBos specified. So, if you want to upgrade some things and install new things with the same command, then you would use the -N flag. Note that upgrades are handled prior to new installs.
.RE
.P
-r
.RS
Skip viewing of the README and the yes or no question which accompanies it. Anytime sboupgrade or sboinstall is run, the first thing the command will attempt to do is show you the README for a given SBo and ask whether or not you wish to proceed; this option skips the README and bypasses the question. If multiple SBos are specified, this option bypasses them all.
.RE
.P
-i
.RS
Do not actually install the package created at the end of the build process. So, the SlackBuild will be run, and the package will be left in /tmp, or in $PKG_DIR if so defined (see sboconfig(1) and sbotools.conf(5)).
.RE
.P
-v
.RS
Show sbotools version information.
.RE
.SH BUGS
.P
- Installing compat-32 packages on 64-bit systems is currently impossible.
.P
- It is currently not possible to specify how many concurrent jobs make should run (make's -j flag).
.P
- Probably more that I've missed. Please report any found to j@dawnrazor.net; patches are always welcome. In the future sbotools may exist in a public git repository and this section may change to reflect that.
.SH SEE ALSO
.P
sbocheck(1), sboconfig(1), sbofind(1), sbosnap(1), sbotools.conf(5)
.SH AUTHOR
.P
Jacob Pipkin <j@dawnrazor.net>
