.TH sbosnap 1 "Sweetmorn, the 73rd day of Discord in the YOLD 3178" "sbotools 0.4 fnord" dawnrazor.net
.SH NAME
.P
sbosnap - slackbuilds.org tree fetch and update command.
.SH SYNAPSES
.P
sbosnap [-v] (fetch|update)
.SH DESCRIPTION
.P
sbosnap is used to download and update a local copy of the slackbuilds.org tree, minus the .tar.gz{,.asc} files. Note that sbocheck(1) will also update the tree, and will then also check for updated slackbuilds. rsync is used for both operations.
.SH OPTIONS
.P
fetch
.RS
Download a local copy of the slackbuilds.org tree. The copy will be downloaded to the SBO_HOME setting (see sboconfig(1) and sbotools.conf(5)), which, by default, is /usr/sbo
.RE
.P
update
.RS
Update an previously fetch'd copy of the slackbuilds.org tree.
.RE
.P
-v
.RS
Show sbotools version information.
.RE

.SH BUGS
.P
None known, but there may be some. Please report any found to j@dawnrazor.net; patches are always welcome. In the future sbotools may exist in a public git repository and this section may change to reflect that.
.SH SEE ALSO
.P
sbocheck(1), sboconfig(1), sbofind(1), sboinstall(1), sboupgrade(1), sbotools.conf(5)
.SH AUTHOR
.P
Jacob Pipkin <j@dawnrazor.net>
