#!/usr/bin/env perl
#
# sboinstall
# script to install a SlackBuild by name
#
# author: Jacob Pipkin <j@dawnrazor.net>
# date: Pungenday, the 40th day of Discord in the YOLD 3178
# license: WTFPL <http://sam.zoy.org/wtfpl/COPYING>

use SBO::Lib;
use Getopt::Std;
use File::Basename;
use strict;
use warnings FATAL => 'all';

my $self = basename ($0);

sub show_usage {
	print <<EOF
Usage: $self [options] sbo

Options:
  -h: this screen.
  -v: version information.
  -c: do not clean working files/directories after the build.                   
  -d: clean distfiles afterward. 
  -i: do not run installpkg at the end of the build process.
  -j: specify "-j" setting to make, for SMP systems; overrides conf file.
  -p: install an SBo as a -compat32 pkg on a multilib x86_64 system.
  -r: skip viewing of the SBo README.

EOF
}

my %options;
getopts ('hvcdripj:',\%options);

show_usage () and exit(0) if exists $options{h};
show_version () and exit(0) if exists $options{v};

show_usage () and exit (0) unless exists $ARGV[0];

my @opts = ('c','d','r','i','p','j');
for my $opt (@opts) {
	unshift (@ARGV,"-$opt") if exists $options{$opt};
}

my $string = '';
for my $arg (@ARGV) {
	$string .= " $arg";
}

system ("/usr/sbin/sboupgrade -oN $string");
exit 0;
