#!/usr/bin/perl
#
# vim: set ts=4:noet
#
# sbosnap
# script to pull down / update a local copy of the slackbuilds.org tree.
#
# authors: Jacob Pipkin <j@dawnrazor.net>
#          Luke Williams <xocel@iquidus.org>
#          Andreas Guldstrand <andreas.guldstrand@gmail.com>
# license: WTFPL <http://sam.zoy.org/wtfpl/COPYING>

use 5.16.0;
use strict;
use warnings FATAL => 'all';
use SBO::Lib qw/ fetch_tree update_tree %config /;
use File::Basename;
use Getopt::Long;

my $sbo_home = $config{SBO_HOME};
my $self = basename($0);

sub show_usage {
	print <<EOF
Usage: $self [options|command]

Options:
  -h|--help:
    this screen.
  -v|--version:
    version information.

Commands:
  fetch: initialize a local copy of the slackbuilds.org tree.
  update: update an existing local copy of the slackbuilds.org tree.
          (generally, you may prefer "sbocheck" over "$self update")

EOF
}

show_usage() and exit 1 unless exists $ARGV[0];

my ($help, $vers);

GetOptions('help|h' => \$help, 'version|v' => \$vers);

show_usage() and exit 0 if $help;
show_version() and exit 0 if $vers;

# check for a command and, if found, execute it
my $command;
if ($ARGV[0] =~ /fetch|update/) {
	$command = $ARGV[0];
} else { 
	show_usage() and exit 1;
}

if    ($command eq 'fetch')  { fetch_tree() }
elsif ($command eq 'update') { update_tree() }

exit 0;
